// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'radio-menu'
  | 'radio-menu-left'
  | 'radio-menu-right'
  | 'radio-menu-top';
